### ISSUE TITLE
Uncontrolled data used in path expression

### ISSUE THREAD

**Issue by smthbh** [b43r/calibre-web#1]
https://github.com/b43r/calibre-web/blob/bc6517246acb8cc3fddbe50b3870bc84b64e8046/CalibreWeb/Controllers/DownloadController.cs#L38

User provided input flows to here and is used in a path.

Accessing paths controlled by users can allow an attacker to access unexpected resources. This can result in sensitive information being revealed or deleted, or an attacker being able to influence behavior by modifying unexpected files.

Example
A malicious user could base64 encode a filename which contains special characters. For example, the string "../../etc/passwd" will result in the code reading the file located at "/home/[user]/../../etc/passwd", which is the system's password file. This file would then be sent back to the user, giving them access to all the system's passwords.

References
OWASP: [Path Traversal](https://owasp.org/www-community/attacks/Path_Traversal).
Common Weakness Enumeration: [CWE-22](https://cwe.mitre.org/data/definitions/22.html).
Common Weakness Enumeration: [CWE-23](https://cwe.mitre.org/data/definitions/23.html).
Common Weakness Enumeration: [CWE-36](https://cwe.mitre.org/data/definitions/36.html).
Common Weakness Enumeration: [CWE-73](https://cwe.mitre.org/data/definitions/73.html).
Common Weakness Enumeration: [CWE-99](https://cwe.mitre.org/data/definitions/99.html).

**Comment by b43r** [comment]
Fixed with latest commits
